### ISSUE TITLE
Issues using the (nuget version) DDPClient on Windows Phone 8.1

### ISSUE THREAD

**Issue by Melakith** [sonyarouje/DDPClient.NET#8]
Hey Sony,

we're having some trouble using your package for our App. When we try to tun the sample code, we get the following exception:

<pre><code>

       IDataSubscriber subscriber = new Subscriber();
		DDPClient client = new DDPClient(sub);

		client.Connect("localhost:3000");
		client.Subscribe("allproducts");
	}
	
    public class Subscriber:IDataSubscriber
    {
        public void DataReceived(dynamic data)
        {
            try
            {
                if (data.type == "sub")
                {
                    Console.WriteLine(data.prodCode + ": " + data.prodName + ": collection: " + data.collection);
                }
            }
            catch(Exception ex)
            {
                throw;
            }
        }
</code></pre>
System.IO.FileNotFoundException
  HResult=-2147024894
  Message=Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
  Source=DDPClient.Net
  FileName=System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  StackTrace:
       at Net.DDP.Client.ResultQueue..ctor(IDataSubscriber subscriber)
       at Net.DDP.Client.DDPClient..ctor(IDataSubscriber subscriber)
       at YT_Player_Test.MainPage.<OnNavigatedTo>d__0.MoveNext()
  InnerException:

**Comment by sonyarouje** [comment]
Can you please tell me which version of the Visual studio you are using? Also I am not much active with this project as of now.

**Comment by Melakith** [comment]
We are using VS 2013 Ultimate. 

 We were also trying to just use the project directly from Github instead of the nuget package, as it was mentioned in another issue, but with other problems coming up.
One was about Threads, which seem not to be available for WP8.1. Another one was, that we couldn't make custom references to the dll's.

And by the way, thanks for the fast response.

**Comment by FlorianPaust** [comment]
Sony, can we expect some help from your side the next time or not? It's no problem if not, but we have to know that we can find another solution and tell our project head.

Regards
